---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[GEN-AI] Chat-qna-core-CI"
run-name: "[GEN-AI-Chat-qna-core-CI] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"


# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches:
      - ciscans-makefile
    paths:
      - 'sample-applications/chat-question-and-answer-core/**'

jobs:
  
  setup:
    runs-on: ubuntu-22.04-32core-128GB
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709

      - name: Generate scan matrix from Makefile
        id: set-matrix
        working-directory: sample-applications/chat-question-and-answer-core
        run: echo "matrix=$(make get-scan-matrix-json)" >> $GITHUB_OUTPUT

  # Job 2: Build AND Scan each component in parallel
  build_and_scan:
    runs-on: ubuntu-22.04-32core-128GB
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      
      - name: Run Trivy Filesystem Scan
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        id: trivy-fs
        with:
          scan_type: "fs"  
          scan-scope: "all"  
          severity: "HIGH,CRITICAL" 
          format: "json"
          scan_target: "sample-applications/chat-question-and-answer-core/"
          report_suffix: "-fs-chat-qna-core-CT7"

      - name: Build Docker image for ${{ matrix.name }}
        working-directory: sample-applications/chat-question-and-answer-core
        run: make build-${{ matrix.name }}

      - name: Run Trivy Image Scan - ${{ matrix.name }} (HTML)
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_target: ${{ matrix.image }}
          scan_type: "image"  
          scan-scope: "all"
          severity: "HIGH,CRITICAL"  
          format: "table"
          generate_sbom: "false"
          report_suffix: "-image-${{ matrix.name }}-html"

      - name: Run Trivy Image Scan - ${{ matrix.name }} (SPDX)
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_target: ${{ matrix.image }}
          scan_type: "image"  
          scan-scope: "all"
          severity: "HIGH,CRITICAL"  
          format: "spdx-json"
          scanners: "vuln"
          generate_sbom: "false"
          report_suffix: "-image-${{ matrix.name }}-spdx"

      - name: Scan Dockerfile - ${{ matrix.name }}
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@27276444a9bcf247a27369406686b689933bd1ff
        with:
          scan_type: "config"
          scan_target: ${{ matrix.context }}
          severity: "HIGH,CRITICAL"
          format: "json"
          misconfig_scanners: "dockerfile"
          report_suffix: "-config-${{ matrix.name }}"
          working_dir: "sample-applications/chat-question-and-answer-core/"

      - name: Upload Trivy Report for ${{ matrix.name }}
        uses: actions/upload-artifact@de65e23aa2b7e23d713bb51fbfcb6d502f8667d8
        with:
          name: trivy-report-${{ matrix.name }}
          path: security-results/trivy*